---
title: "captcha"
output: html_document
---

```{r setup, echo=T, results='hide', error=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts = list(width.cutoff = 60), tidy = TRUE)

library(Sleuth3) # example datasets from textbook, "The Statistical Sleuth - A Course in 
# Methods of Data Analysis (3rd Edition)"
library(reshape2) # for formatting and aggregation of data frames
library(ggplot2) # for creating graphs
library(dplyr) # for data manipulation and clean-up
library(plotly) # for creating interactive web graphics from ggplot2 graphs
library(knitr) # required for generating PDF output
library(modeest) # required for `mfv()` function
#install.packages('nortest')
library(nortest)
library(truncnorm)
```



```{r}
################## Set-1 Accurate ###########################

set1_accurate <- read.csv("accurate1.csv")
#set1_accurate

#boost set1 older accurate
options(digits = 4)
Expandedset1_accurate_older <- round(rtruncnorm(25,a=0,b=10, mean=mean(set1_accurate$older), sd=2))
Expandedset1_accurate_older
#boost set1 younger accurate
Expandedset1_accurate_younger <- round(rtruncnorm(25,a=0,b=10, mean=mean(set1_accurate$younger), sd=2))
Expandedset1_accurate_younger

# compare the mean
mean(set1_accurate$older)
mean(Expandedset1_accurate_older)

ad.test(Expandedset1_accurate_older)
ad.test(Expandedset1_accurate_younger)

data <- data.frame(older = c(Expandedset1_accurate_older), younger = c(Expandedset1_accurate_younger))
data
#reshape the form
set1_acc <- melt(data, measure.vars = c("older", "younger"))
names(set1_acc) <- c("group", "accurate")
write.csv(set1_acc, file = "set1_acc.csv")
set1_acc
boxplot(set1_accurate)
#t-test
t.test(set1_acc$accurate ~ set1_acc$group, alternative = "two.side", var.equal = FALSE)

#Test and report for significance at 0.05.
#assume that the older group has low accurate than the younger group
#Since the p-value<0.05, we cannot reject h0.????
```
```{r}
################## Set-2 Accurate ###########################

set2_accurate <- read.csv("accurate2.csv")
#set2_accurate

#boost set2 older accurate
options(digits = 4)
Expandedset2_accurate_older <- round(rtruncnorm(25,a=0,b=10, mean=mean(set2_accurate$older), sd=2))
Expandedset2_accurate_older
#boost set2 younger accurate
Expandedset2_accurate_younger <- round(rtruncnorm(25,a=0,b=10, mean=mean(set2_accurate$younger), sd=2))
Expandedset2_accurate_younger

# compare the mean
mean(set2_accurate$older)
mean(Expandedset2_accurate_older)

ad.test(Expandedset2_accurate_older)
ad.test(Expandedset2_accurate_younger)

data <- data.frame(older = c(Expandedset2_accurate_older), younger = c(Expandedset2_accurate_younger))
data
#reshape the form
set2_acc <- melt(data, measure.vars = c("older", "younger"))
names(set2_acc) <- c("group", "accurate")
write.csv(set2_acc, file = "set2_acc.csv")
set2_acc
boxplot(set2_accurate)
#t-test
ad.test(set2_acc$accurate)
t.test(set2_acc$accurate ~ set2_acc$group, alternative = "two.side", var.equal = FALSE)
```

```{r}
################## Set-3 Accurate ###########################

set3_accurate <- read.csv("accurate3.csv")
#set3_accurate

#boost set3 older accurate
options(digits = 4)
Expandedset3_accurate_older <- round(rtruncnorm(25,a=0,b=10, mean=mean(set3_accurate$older), sd=2))
Expandedset3_accurate_older
#boost set3 younger accurate
Expandedset3_accurate_younger <- round(rtruncnorm(25,a=0,b=10, mean=mean(set3_accurate$younger), sd=2))
Expandedset3_accurate_younger

# compare the mean
mean(set3_accurate$older)
mean(Expandedset3_accurate_older)
ad.test(Expandedset3_accurate_older)
ad.test(Expandedset3_accurate_younger)
data <- data.frame(older = c(Expandedset3_accurate_older), younger = c(Expandedset3_accurate_younger))
data
#reshape the form
set3_acc <- melt(data, measure.vars = c("older", "younger"))
names(set3_acc) <- c("group", "accurate")
write.csv(set3_acc, file = "set3_acc.csv")
set3_acc
boxplot(set3_accurate)
#t-test
t.test(set3_acc$accurate ~ set3_acc$group, alternative = "two.side", var.equal = FALSE)
```
```{r}
################## Set-4 Accurate ###########################

set4_accurate <- read.csv("accurate4.csv")
#set4_accurate

#boost set4 older accurate
options(digits = 4)
Expandedset4_accurate_older <- round(rtruncnorm(25,a=0,b=10, mean=mean(set4_accurate$older), sd=2))
Expandedset4_accurate_older
#boost set4 younger accurate
Expandedset4_accurate_younger <- round(rtruncnorm(25,a=0,b=10, mean=mean(set4_accurate$younger), sd=2))
Expandedset4_accurate_younger

# compare the mean
mean(set4_accurate$older)
mean(Expandedset4_accurate_older)
ad.test(Expandedset4_accurate_older)
ad.test(Expandedset4_accurate_younger)

data <- data.frame(older = c(Expandedset4_accurate_older), younger = c(Expandedset4_accurate_younger))
data
#reshape the form
set4_acc <- melt(data, measure.vars = c("older", "younger"))
names(set4_acc) <- c("group", "accurate")
write.csv(set4_acc, file = "set4_acc.csv")
set4_acc
boxplot(set4_accurate)
#t-test

t.test(set4_acc$accurate ~ set4_acc$group, alternative = "two.side", var.equal = FALSE)
```

```{r}
################## Set-1 Time ############################
set1_time <- read.csv("time1.csv")

#boost set1 older time
options(digits = 4)
Expandedset1_time_older <- rnorm(25, mean=mean(set1_time$older), sd=2)
Expandedset1_time_older
#boost set1 younger time
Expandedset1_time_younger <- rnorm(25, mean=mean(set1_time$younger), sd=2)
Expandedset1_time_younger

# compare the mean
mean(set1_time$older)
mean(Expandedset1_time_older)

data <- data.frame(older = c(Expandedset1_time_older), younger = c(Expandedset1_time_younger))
data
#reshape the form
set1_ti <- melt(data, measure.vars = c("older", "younger"))
names(set1_ti) <- c("group", "time")
write.csv(set1_ti, file = "set1_ti.csv")
set1_ti
ad.test(Expandedset1_time_older)
ad.test(Expandedset1_time_younger)
boxplot(set1_time)
#t-test
set1_ti <- read.csv("set1_ti.csv")
ad.test(set1_ti$time)
t.test(set1_ti$time ~ set1_ti$group, alternative = "two.side", var.equal = FALSE)

```
```{r}
```


```{r}
################## Set-2 Time ############################
set2_time <- read.csv("time2.csv")

#boost set2 older time
options(digits = 4)
Expandedset2_time_older <- rnorm(25, mean=mean(set2_time$older), sd=2)
Expandedset2_time_older
#boost set2 younger time
Expandedset2_time_younger <- rnorm(25, mean=mean(set2_time$younger), sd=2)
Expandedset2_time_younger

# compare the mean
mean(set2_time$older)
mean(Expandedset2_time_older)

data <- data.frame(older = c(Expandedset2_time_older), younger = c(Expandedset2_time_younger))
data
#reshape the form
set2_ti <- melt(data, measure.vars = c("older", "younger"))
names(set2_ti) <- c("group", "time")
write.csv(set2_ti, file = "set2_ti.csv")
set2_ti
ad.test(Expandedset2_time_older)
ad.test(Expandedset2_time_younger)
boxplot(set2_time)
#t-test
t.test(set2_ti$time ~ set2_ti$group, alternative = "two.side", var.equal = FALSE)
```


```{r}
################## Set-3 Time ############################
set3_time <- read.csv("time3.csv")

#boost set3 older time
options(digits = 4)
Expandedset3_time_older <- rnorm(25, mean=mean(set3_time$older), sd=2)
Expandedset3_time_older
#boost set3 younger time
Expandedset3_time_younger <- rnorm(25, mean=mean(set3_time$younger), sd=2)
Expandedset3_time_younger

# compare the mean
mean(set3_time$older)
mean(Expandedset3_time_older)

data <- data.frame(older = c(Expandedset3_time_older), younger = c(Expandedset3_time_younger))
data
#reshape the form
set3_ti <- melt(data, measure.vars = c("older", "younger"))
names(set3_ti) <- c("group", "time")
write.csv(set3_ti, file = "set3_ti.csv")
set3_ti
ad.test(Expandedset3_time_older)
boxplot(set3_time)
#t-test
t.test(set3_ti$time ~ set3_ti$group, alternative = "two.side", var.equal = FALSE)
```
```{r}
################## Set-4 Time ############################
set4_time <- read.csv("time4.csv")

#boost set4 older time
options(digits = 4)
Expandedset4_time_older <- rnorm(25, mean=mean(set4_time$older), sd=2)
Expandedset4_time_older
#boost set4 younger time
Expandedset4_time_younger <- rnorm(25, mean=mean(set4_time$younger), sd=2)
Expandedset4_time_younger

# compare the mean
mean(set4_time$older)
mean(Expandedset4_time_older)

data <- data.frame(older = c(Expandedset4_time_older), younger = c(Expandedset4_time_younger))
data
#reshape the form
set4_ti <- melt(data, measure.vars = c("older", "younger"))
names(set4_ti) <- c("group", "time")
write.csv(set4_ti, file = "set4_ti.csv")
set4_ti
boxplot(set4_time)
#t-test
t.test(set4_ti$time ~ set4_ti$group, alternative = "two.side", var.equal = FALSE)
```
haha
```{r}
################## old Accurate ###########################

old_accurate <- read.csv("olderaccurate.csv")
#older_accurate

#boost older set1 accurate
options(digits = 4)
Expandedold_accurate_set1 <- round(rtruncnorm(25,a=0,b=10, mean=mean(old_accurate$set1), sd=2))
Expandedold_accurate_set1
#boost older set2 accurate
Expandedold_accurate_set2 <- round(rtruncnorm(25,a=0,b=10, mean=mean(old_accurate$set2), sd=2))
Expandedold_accurate_set2

#boost older set3 accurate
Expandedold_accurate_set3 <- round(rtruncnorm(25,a=0,b=10, mean=mean(old_accurate$set3), sd=2))
Expandedold_accurate_set3

#boost older set4 accurate
Expandedold_accurate_set4 <- round(rtruncnorm(25,a=0,b=10, mean=mean(old_accurate$set4), sd=2))
Expandedold_accurate_set4

data <- data.frame(set1 = c(Expandedold_accurate_set1), set2 = c(Expandedold_accurate_set2), set3 = c(Expandedold_accurate_set3), set4 = c(Expandedold_accurate_set4))
data
#reshape the form
old_acc <- melt(data, measure.vars = c("set1", "set2", "set3", "set4"))
names(old_acc) <- c("set", "accurate")
write.csv(old_acc, file = "old_acc.csv")
old_acc
mean(old_accurate$set1)
mean(old_accurate$set2)
mean(old_accurate$set3)
mean(old_accurate$set4)
boxplot(old_accurate)
model <- aov(old_acc$accurate ~ old_acc$set)
summary(model)
```

```{r}
################## young Accurate ###########################

young_accurate <- read.csv("youngaccurate.csv")
#young_accurate

#boost young set1 accurate
options(digits = 4)
Expandedyoung_accurate_set1 <- round(rtruncnorm(25,a=0,b=10, mean=mean(young_accurate$set1), sd=2))
Expandedyoung_accurate_set1
#boost young set2 accurate
Expandedyoung_accurate_set2 <- round(rtruncnorm(25,a=0,b=10, mean=mean(young_accurate$set2), sd=2))
Expandedyoung_accurate_set2

#boost young set3 accurate
Expandedyoung_accurate_set3 <- round(rtruncnorm(25,a=0,b=10, mean=mean(young_accurate$set3), sd=2))
Expandedyoung_accurate_set3

#boost young set4 accurate
Expandedyoung_accurate_set4 <- round(rtruncnorm(25,a=0,b=10, mean=mean(young_accurate$set4), sd=2))
Expandedyoung_accurate_set4

data <- data.frame(set1 = c(Expandedyoung_accurate_set1), set2 = c(Expandedyoung_accurate_set2), set3 = c(Expandedyoung_accurate_set3), set4 = c(Expandedyoung_accurate_set4))
data
#reshape the form
young_acc <- melt(data, measure.vars = c("set1", "set2", "set3", "set4"))
names(young_acc) <- c("set", "accurate")
young_acc
mean(young_accurate$set1)
mean(young_accurate$set2)
mean(young_accurate$set3)
mean(young_accurate$set4)

write.csv(young_acc, file = "young_acc.csv")
boxplot(young_accurate)
model <- aov(young_acc$accurate ~ young_acc$set)
summary(model)
```
```{r}
################## young time ###########################

young_time <- read.csv("youngtime.csv")
#young_time

#boost young set1 time
options(digits = 4)
Expandedyoung_time_set1 <- rnorm(25, mean=mean(young_time$set1), sd=2)
Expandedyoung_time_set1
#boost young set2 time
Expandedyoung_time_set2 <- rnorm(25, mean=mean(young_time$set2), sd=2)
Expandedyoung_time_set2

#boost young set3 time
Expandedyoung_time_set3 <- rnorm(25, mean=mean(young_time$set3), sd=2)
Expandedyoung_time_set3

#boost young set4 time
Expandedyoung_time_set4 <- rnorm(25, mean=mean(young_time$set4), sd=2)
Expandedyoung_time_set4

data <- data.frame(set1 = c(Expandedyoung_time_set1), set2 = c(Expandedyoung_time_set2), set3 = c(Expandedyoung_time_set3), set4 = c(Expandedyoung_time_set4))
data
#reshape the form
young_ti <- melt(data, measure.vars = c("set1", "set2", "set3", "set4"))
names(young_ti) <- c("set", "time")
young_ti
mean(young_time$set1)
mean(young_time$set2)
mean(young_time$set3)
mean(young_time$set4)
write.csv(young_ti, file = "young_ti.csv")
boxplot(young_time)
model <- aov(young_ti$time ~ young_ti$set)
summary(model)
```
hhh
```{r}
old_time <- read.csv("oldtime.csv")
#older_time

#boost older set1 time
options(digits = 4)
Expandedold_time_set1 <- rnorm(25, mean=mean(old_time$set1), sd=2)
Expandedold_time_set1
#boost older set2 time
Expandedold_time_set2 <- rnorm(25, mean=mean(old_time$set2), sd=2)
Expandedold_time_set2

#boost older set3 time
Expandedold_time_set3 <- rnorm(25, mean=mean(old_time$set3), sd=2)
Expandedold_time_set3

#boost older set4 time
Expandedold_time_set4 <- rnorm(25, mean=mean(old_time$set4), sd=2)
Expandedold_time_set4

data <- data.frame(set1 = c(Expandedold_time_set1), set2 = c(Expandedold_time_set2), set3 = c(Expandedold_time_set3), set4 = c(Expandedold_time_set4))
data
#reshape the form
old_ti <- melt(data, measure.vars = c("set1", "set2", "set3", "set4"))
names(old_ti) <- c("set", "time")
old_ti
mean(old_time$set1)
mean(old_time$set2)
mean(old_time$set3)
mean(old_time$set4)
boxplot(old_time)
write.csv(old_ti, file = "old_ti.csv")
model <- aov(old_ti$time ~ old_ti$set)
summary(model)
```

```{r}
alltime <- read.csv("all-time.csv")
summary(aov(time ~ set + group, data=alltime))
model <- aov(time ~ set + group, data=alltime)
TukeyHSD(model)
re <- TukeyHSD(model)
plot(re)
```
hh
```{r}
allaccuracy <- read.csv("all-accuracy.csv")
summary(aov(accurate ~ set + group, data=allaccuracy))
model <- aov(accurate ~ set + group, data=allaccuracy)
re <- TukeyHSD(model)
plot(re)
```

